### ISSUE TITLE
New documentation site doesn't get systems right

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap-Manual#2]
Compare the syntax check exercises on

https://carnap.github.io/Carnap-Manual/quickstart.html and
https://carnap.io/srv/doc/quickstart.md

On the former, the first exercise has the wrong symbols (should have & and horseshoe).

**Comment by gleachkr** [comment]
Thanks! Forgot to pass attributes forward in the new syntax-checker filter. Should be fixed by 7950ee2.
